export const LOCATIONS=[
    "Miyapur",
    "Kukatpally",
    "Nizampet",
    "Chanda Nagar",
    "Lingampally",
    "Patancheru",
    "Pragathi Nagar",
    "KPHB",
    "Bachupally",
    "Beeramguda",
    "Manikonda",
    "Banjara Hills",
    "Jubilee Hills",
    "Gowliguda",
    "Kothaguda",
    "Kondapur",
    "Gachibowli",
    "Madhapur",
    "Attapur",
    "Shaikpet",
    "Panjagutta",
    "Ameerpet",
    "SR Nagar",
    "Erragadda",
    "Tolichowki",
    "Mehidipatnam",
    "Secunderabad",
    "Tirumalagiri",
    "Abids",
    "Koti",
    "Khairtabad",
    "Nampally",
    "Lakdikapul",
    "Charminar",
    "Uppal",
    "Malakpet",
    "Dilsukhnagar",
    "LB Nagar",
    "Vanastalipuram",
    "Golconda",
    "Suchitra",
    "Shamshabad",
    "Mallapur",
    "Habsiguda",
    "Shamirpet",
    "Quthbullapur",
    "Afzalgunj",
    "Alwal",
    "Amberpet",
    "Bahadurpura",
    "Basheerbagh",
    "Charlapally",
    "ECIL",
    "Himayat Nagar",
    "Jagadgirigutta",
    "Jeedimetla",
    "Kachiguda",
    "Kothapet",
    "Nagole",
    "Bowenpally",
    "RTC X Road",
]

export const PROPERTY_TYPE=[
    "1BHk", 
    "2BHK",
    "3BHK",
    "4BHK",
    "Individual House",
    "Villa ",
    "CommercialProperty"
]